### ISSUE TITLE
Finalize technology list

### ISSUE THREAD

**Issue by NathanBland** [NathanBland/Sprout#1]
What technologies will be used, such as node, mongo, express, or others. This is intended to be a core list, and not an exhaustive one.

Currently the list looks like:
- node (server)
- hapi (mvc)
- mongo? (db) 
- Other?

**Comment by Malachi-M** [comment]
Let me know any of your thoughts on these proposed technologies.

#### Server

I like the proposed server technology. I would definitely consider something outside of this server stack, but since we have spent the most time here, it feels safer in regard to meeting a deadline.

#### Back-End Framework

Lets assume with carry on with Node as our server. I really like the idea of branching out a little and trying some additional framework options. In this case, that looks like the [Hapi MVC](http://hapijs.com/)

#### Datastore

I believe given our time constraints it would be best to move forward with the MongoDB + Mongoose ODM pairing that we previously implemented. It would be great to be able to implement CouchDB. I am not sure that time will afford us that option.

#### Templating Engine

I would be interested in trying out Jinja or similar engine for templating our views. Here is an option that is allegedly similar to Jinja, [Swig](http://paularmstrong.github.io/swig/). Additionally, here is a claimed 'port' of Jinja2 over to JavaScript [Nunjucks](http://mozilla.github.io/nunjucks/)

#### CSS Framework

I am interested in utilizing [Kube](http://imperavi.com/kube/css/) or [Pure](http://purecss.io/) as frameworks for our styling as this will provide out of the box cross browser standardization for styles. This will prove to be a boon for us with our timeline.

#### Build Systems

Should we astonish ourselves with unanticipated levels of progress, it would be a good exercise for us to implement a build system such as [Grunt](http://gruntjs.com/) or [Gulp](http://gulpjs.com/). What are your thoughts?

#### Optimization

I believe it would be interesting to optimize our server, files, and data as much as possible.  This may allow us to attempt different techniques such as minifying html, js, and css.
- CSS
  - [UnCSS](https://github.com/giakki/uncss)
- JS
  - [Uglify ver. 2](https://github.com/mishoo/UglifyJS2)

**Comment by NathanBland** [comment]
I think we agree on server, back-end, and datastore. 

Templating engines look interesting to me, and I'm more than willing tot try out swig, as in looking over its documentation it appears easy to pick up and use.

CSS framework doesn't really matter to me, I'm fine with either kube or Pure. I'm far more familiar with pure, but kube looks pretty easy to pick up too. I do like that it bundles itself with [font-awesome](http://fortawesome.github.io/Font-Awesome/) for icons, which are fantastic.

Build systems are one area I'm extremely unfamiliar with, so I'll need to do some reading on that.

Optimization is all fine and good, but I think that will be a final focus, as debugging compressed code doesn't sound like a fun thing to do.
